import type { College, ProfessionRanking, UserRanking } from "./types"

export const mockColleges: College[] = [
  {
    id: "1",
    name: "Stanford University",
    location: "Stanford, CA",
    type: "private",
    size: "medium",
    tuition: 56169,
    acceptanceRate: 4.3,
    averageGPA: 3.96,
    averageSAT: 1505,
    image: "/stanford-university-campus.png",
    description: "A leading research university known for innovation and entrepreneurship.",
    majors: ["Computer Science", "Engineering", "Business", "Medicine", "Law"],
    overallRating: 4.8,
    totalVotes: 2847,
    firstChoiceVotes: 1247,
  },
  {
    id: "2",
    name: "MIT",
    location: "Cambridge, MA",
    type: "private",
    size: "medium",
    tuition: 53790,
    acceptanceRate: 6.7,
    averageGPA: 3.91,
    averageSAT: 1535,
    image: "/mit-campus-building.jpg",
    description: "World-renowned for science, technology, engineering, and mathematics.",
    majors: ["Computer Science", "Engineering", "Physics", "Mathematics", "Economics"],
    overallRating: 4.7,
    totalVotes: 3156,
    firstChoiceVotes: 1156,
  },
  {
    id: "3",
    name: "Harvard University",
    location: "Cambridge, MA",
    type: "private",
    size: "medium",
    tuition: 54269,
    acceptanceRate: 3.4,
    averageGPA: 3.98,
    averageSAT: 1520,
    image: "/harvard-university-campus-yard.jpg",
    description: "Prestigious Ivy League institution with a rich history and tradition.",
    majors: ["Liberal Arts", "Business", "Law", "Medicine", "Government"],
    overallRating: 4.6,
    totalVotes: 4203,
    firstChoiceVotes: 1834,
  },
  {
    id: "4",
    name: "UC Berkeley",
    location: "Berkeley, CA",
    type: "public",
    size: "large",
    tuition: 14226,
    acceptanceRate: 16.3,
    averageGPA: 3.89,
    averageSAT: 1415,
    image: "/uc-berkeley-campus-tower.jpg",
    description: "Top public research university with strong programs across disciplines.",
    majors: ["Engineering", "Computer Science", "Business", "Liberal Arts", "Sciences"],
    overallRating: 4.5,
    totalVotes: 5672,
    firstChoiceVotes: 987,
  },
  {
    id: "5",
    name: "Carnegie Mellon",
    location: "Pittsburgh, PA",
    type: "private",
    size: "medium",
    tuition: 58924,
    acceptanceRate: 15.4,
    averageGPA: 3.84,
    averageSAT: 1490,
    image: "/carnegie-mellon-university-campus.jpg",
    description: "Leading institution for computer science, engineering, and the arts.",
    majors: ["Computer Science", "Engineering", "Business", "Fine Arts", "Drama"],
    overallRating: 4.4,
    totalVotes: 2891,
    firstChoiceVotes: 743,
  },
  {
    id: "6",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    type: "public",
    size: "large",
    tuition: 11448,
    acceptanceRate: 31.8,
    averageGPA: 3.71,
    averageSAT: 1365,
    image: "/ut-austin-campus-tower.jpg",
    description: "Large public research university with strong programs and vibrant campus life.",
    majors: ["Business", "Engineering", "Liberal Arts", "Communications", "Education"],
    overallRating: 4.3,
    totalVotes: 7234,
    firstChoiceVotes: 634,
  },
  {
    id: "7",
    name: "Yale University",
    location: "New Haven, CT",
    type: "private",
    size: "medium",
    tuition: 59950,
    acceptanceRate: 4.6,
    averageGPA: 3.95,
    averageSAT: 1515,
    image: "/yale-university-campus.jpg",
    description: "Prestigious Ivy League university known for liberal arts and leadership.",
    majors: ["Liberal Arts", "Law", "Medicine", "Drama", "History"],
    overallRating: 4.7,
    totalVotes: 3421,
    firstChoiceVotes: 856,
  },
  {
    id: "8",
    name: "Princeton University",
    location: "Princeton, NJ",
    type: "private",
    size: "medium",
    tuition: 56010,
    acceptanceRate: 3.9,
    averageGPA: 3.97,
    averageSAT: 1520,
    image: "/princeton-university-campus.jpg",
    description: "Elite Ivy League institution with strong undergraduate focus.",
    majors: ["Liberal Arts", "Engineering", "Economics", "Public Policy", "Physics"],
    overallRating: 4.8,
    totalVotes: 2987,
    firstChoiceVotes: 923,
  },
  {
    id: "9",
    name: "Caltech",
    location: "Pasadena, CA",
    type: "private",
    size: "small",
    tuition: 58680,
    acceptanceRate: 6.4,
    averageGPA: 3.93,
    averageSAT: 1545,
    image: "/caltech-campus.png",
    description: "Small, elite institution focused on science and engineering.",
    majors: ["Engineering", "Physics", "Computer Science", "Mathematics", "Chemistry"],
    overallRating: 4.6,
    totalVotes: 1234,
    firstChoiceVotes: 456,
  },
  {
    id: "10",
    name: "Columbia University",
    location: "New York, NY",
    type: "private",
    size: "medium",
    tuition: 61850,
    acceptanceRate: 5.1,
    averageGPA: 3.94,
    averageSAT: 1510,
    image: "/columbia-university-campus.png",
    description: "Ivy League university in the heart of Manhattan.",
    majors: ["Journalism", "Business", "Engineering", "Liberal Arts", "Medicine"],
    overallRating: 4.5,
    totalVotes: 3876,
    firstChoiceVotes: 567,
  },
  {
    id: "11",
    name: "University of Chicago",
    location: "Chicago, IL",
    type: "private",
    size: "medium",
    tuition: 59298,
    acceptanceRate: 7.4,
    averageGPA: 3.92,
    averageSAT: 1520,
    image: "/university-of-chicago-campus.png",
    description: "Renowned for rigorous academics and intellectual discourse.",
    majors: ["Economics", "Liberal Arts", "Business", "Medicine", "Law"],
    overallRating: 4.4,
    totalVotes: 2654,
    firstChoiceVotes: 489,
  },
  {
    id: "12",
    name: "Northwestern University",
    location: "Evanston, IL",
    type: "private",
    size: "medium",
    tuition: 58701,
    acceptanceRate: 9.3,
    averageGPA: 3.88,
    averageSAT: 1490,
    image: "/northwestern-university-campus.png",
    description: "Strong programs in journalism, business, and engineering.",
    majors: ["Journalism", "Business", "Engineering", "Theatre", "Medicine"],
    overallRating: 4.3,
    totalVotes: 3245,
    firstChoiceVotes: 445,
  },
  {
    id: "13",
    name: "Duke University",
    location: "Durham, NC",
    type: "private",
    size: "medium",
    tuition: 58031,
    acceptanceRate: 8.9,
    averageGPA: 3.91,
    averageSAT: 1500,
    image: "/placeholder-vogwf.png",
    description: "Elite university known for academics, research, and athletics.",
    majors: ["Business", "Engineering", "Medicine", "Law", "Public Policy"],
    overallRating: 4.5,
    totalVotes: 2987,
    firstChoiceVotes: 523,
  },
  {
    id: "14",
    name: "University of Pennsylvania",
    location: "Philadelphia, PA",
    type: "private",
    size: "large",
    tuition: 58620,
    acceptanceRate: 8.4,
    averageGPA: 3.9,
    averageSAT: 1495,
    image: "/placeholder-qygao.png",
    description: "Ivy League university with top-ranked business school.",
    majors: ["Business", "Engineering", "Medicine", "Liberal Arts", "Nursing"],
    overallRating: 4.4,
    totalVotes: 4123,
    firstChoiceVotes: 634,
  },
  {
    id: "15",
    name: "Cornell University",
    location: "Ithaca, NY",
    type: "private",
    size: "large",
    tuition: 57222,
    acceptanceRate: 10.9,
    averageGPA: 3.85,
    averageSAT: 1465,
    image: "/placeholder-aypem.png",
    description: "Ivy League university with strong engineering and agriculture programs.",
    majors: ["Engineering", "Agriculture", "Business", "Liberal Arts", "Veterinary"],
    overallRating: 4.3,
    totalVotes: 3654,
    firstChoiceVotes: 378,
  },
  {
    id: "16",
    name: "Brown University",
    location: "Providence, RI",
    type: "private",
    size: "medium",
    tuition: 58504,
    acceptanceRate: 7.7,
    averageGPA: 3.89,
    averageSAT: 1485,
    image: "/brown-university-campus.png",
    description: "Ivy League university known for its open curriculum.",
    majors: ["Liberal Arts", "Computer Science", "International Relations", "Medicine", "Engineering"],
    overallRating: 4.4,
    totalVotes: 2876,
    firstChoiceVotes: 334,
  },
  {
    id: "17",
    name: "Dartmouth College",
    location: "Hanover, NH",
    type: "private",
    size: "medium",
    tuition: 57638,
    acceptanceRate: 8.8,
    averageGPA: 3.87,
    averageSAT: 1480,
    image: "/placeholder-vn96d.png",
    description: "Ivy League college with strong alumni network and outdoor culture.",
    majors: ["Liberal Arts", "Business", "Engineering", "Medicine", "Government"],
    overallRating: 4.3,
    totalVotes: 2543,
    firstChoiceVotes: 298,
  },
  {
    id: "18",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    type: "private",
    size: "medium",
    tuition: 54158,
    acceptanceRate: 11.7,
    averageGPA: 3.83,
    averageSAT: 1470,
    image: "/placeholder-9ihfm.png",
    description: "Elite Southern university with strong academics and social life.",
    majors: ["Liberal Arts", "Engineering", "Business", "Medicine", "Education"],
    overallRating: 4.2,
    totalVotes: 2987,
    firstChoiceVotes: 267,
  },
  {
    id: "19",
    name: "Rice University",
    location: "Houston, TX",
    type: "private",
    size: "small",
    tuition: 51107,
    acceptanceRate: 11.0,
    averageGPA: 3.86,
    averageSAT: 1490,
    image: "/placeholder-43hwx.png",
    description: "Small research university known for engineering and sciences.",
    majors: ["Engineering", "Computer Science", "Business", "Medicine", "Architecture"],
    overallRating: 4.4,
    totalVotes: 1876,
    firstChoiceVotes: 234,
  },
  {
    id: "20",
    name: "Georgetown University",
    location: "Washington, DC",
    type: "private",
    size: "medium",
    tuition: 56058,
    acceptanceRate: 14.5,
    averageGPA: 3.81,
    averageSAT: 1450,
    image: "/placeholder-b67nf.png",
    description: "Prestigious Catholic university known for international affairs.",
    majors: ["International Affairs", "Business", "Liberal Arts", "Law", "Medicine"],
    overallRating: 4.2,
    totalVotes: 3234,
    firstChoiceVotes: 198,
  },
]

export const mockProfessionRankings: ProfessionRanking[] = [
  {
    profession: "Software Engineering",
    colleges: [
      {
        collegeId: "1",
        collegeName: "Stanford University",
        rating: 4.9,
        votes: 1247,
        averageSalary: 165000,
        employmentRate: 98,
      },
      { collegeId: "2", collegeName: "MIT", rating: 4.8, votes: 1456, averageSalary: 162000, employmentRate: 97 },
      {
        collegeId: "5",
        collegeName: "Carnegie Mellon",
        rating: 4.7,
        votes: 892,
        averageSalary: 158000,
        employmentRate: 96,
      },
      {
        collegeId: "4",
        collegeName: "UC Berkeley",
        rating: 4.6,
        votes: 2134,
        averageSalary: 152000,
        employmentRate: 95,
      },
      { collegeId: "9", collegeName: "Caltech", rating: 4.5, votes: 567, averageSalary: 155000, employmentRate: 94 },
      {
        collegeId: "8",
        collegeName: "Princeton University",
        rating: 4.4,
        votes: 743,
        averageSalary: 148000,
        employmentRate: 93,
      },
      {
        collegeId: "3",
        collegeName: "Harvard University",
        rating: 4.3,
        votes: 634,
        averageSalary: 145000,
        employmentRate: 92,
      },
      {
        collegeId: "10",
        collegeName: "Columbia University",
        rating: 4.2,
        votes: 523,
        averageSalary: 142000,
        employmentRate: 91,
      },
      {
        collegeId: "6",
        collegeName: "University of Texas at Austin",
        rating: 4.2,
        votes: 1678,
        averageSalary: 135000,
        employmentRate: 92,
      },
      {
        collegeId: "11",
        collegeName: "University of Chicago",
        rating: 4.1,
        votes: 456,
        averageSalary: 138000,
        employmentRate: 90,
      },
      {
        collegeId: "12",
        collegeName: "Northwestern University",
        rating: 4.0,
        votes: 389,
        averageSalary: 136000,
        employmentRate: 89,
      },
      {
        collegeId: "13",
        collegeName: "Duke University",
        rating: 3.9,
        votes: 345,
        averageSalary: 134000,
        employmentRate: 88,
      },
      {
        collegeId: "14",
        collegeName: "University of Pennsylvania",
        rating: 3.9,
        votes: 298,
        averageSalary: 133000,
        employmentRate: 87,
      },
      {
        collegeId: "15",
        collegeName: "Cornell University",
        rating: 3.8,
        votes: 267,
        averageSalary: 131000,
        employmentRate: 86,
      },
      {
        collegeId: "16",
        collegeName: "Brown University",
        rating: 3.8,
        votes: 234,
        averageSalary: 130000,
        employmentRate: 85,
      },
      {
        collegeId: "17",
        collegeName: "Dartmouth College",
        rating: 3.7,
        votes: 198,
        averageSalary: 128000,
        employmentRate: 84,
      },
      {
        collegeId: "18",
        collegeName: "Vanderbilt University",
        rating: 3.7,
        votes: 176,
        averageSalary: 127000,
        employmentRate: 83,
      },
      {
        collegeId: "19",
        collegeName: "Rice University",
        rating: 3.6,
        votes: 154,
        averageSalary: 125000,
        employmentRate: 82,
      },
      {
        collegeId: "20",
        collegeName: "Georgetown University",
        rating: 3.5,
        votes: 132,
        averageSalary: 123000,
        employmentRate: 81,
      },
      {
        collegeId: "7",
        collegeName: "Yale University",
        rating: 3.4,
        votes: 98,
        averageSalary: 120000,
        employmentRate: 80,
      },
    ],
  },
  {
    profession: "Investment Banking",
    colleges: [
      {
        collegeId: "3",
        collegeName: "Harvard University",
        rating: 4.8,
        votes: 967,
        averageSalary: 175000,
        employmentRate: 94,
      },
      {
        collegeId: "1",
        collegeName: "Stanford University",
        rating: 4.7,
        votes: 743,
        averageSalary: 172000,
        employmentRate: 93,
      },
      {
        collegeId: "14",
        collegeName: "University of Pennsylvania",
        rating: 4.6,
        votes: 856,
        averageSalary: 170000,
        employmentRate: 92,
      },
      {
        collegeId: "10",
        collegeName: "Columbia University",
        rating: 4.5,
        votes: 723,
        averageSalary: 168000,
        employmentRate: 91,
      },
      { collegeId: "2", collegeName: "MIT", rating: 4.5, votes: 456, averageSalary: 168000, employmentRate: 91 },
      {
        collegeId: "13",
        collegeName: "Duke University",
        rating: 4.4,
        votes: 634,
        averageSalary: 165000,
        employmentRate: 90,
      },
      {
        collegeId: "12",
        collegeName: "Northwestern University",
        rating: 4.3,
        votes: 567,
        averageSalary: 162000,
        employmentRate: 89,
      },
      {
        collegeId: "11",
        collegeName: "University of Chicago",
        rating: 4.3,
        votes: 523,
        averageSalary: 160000,
        employmentRate: 88,
      },
      {
        collegeId: "7",
        collegeName: "Yale University",
        rating: 4.2,
        votes: 489,
        averageSalary: 158000,
        employmentRate: 87,
      },
      {
        collegeId: "8",
        collegeName: "Princeton University",
        rating: 4.2,
        votes: 445,
        averageSalary: 157000,
        employmentRate: 86,
      },
      {
        collegeId: "4",
        collegeName: "UC Berkeley",
        rating: 4.1,
        votes: 634,
        averageSalary: 155000,
        employmentRate: 88,
      },
      {
        collegeId: "17",
        collegeName: "Dartmouth College",
        rating: 4.0,
        votes: 378,
        averageSalary: 152000,
        employmentRate: 85,
      },
      {
        collegeId: "16",
        collegeName: "Brown University",
        rating: 3.9,
        votes: 334,
        averageSalary: 150000,
        employmentRate: 84,
      },
      {
        collegeId: "18",
        collegeName: "Vanderbilt University",
        rating: 3.8,
        votes: 298,
        averageSalary: 148000,
        employmentRate: 83,
      },
      {
        collegeId: "15",
        collegeName: "Cornell University",
        rating: 3.8,
        votes: 267,
        averageSalary: 147000,
        employmentRate: 82,
      },
      {
        collegeId: "6",
        collegeName: "University of Texas at Austin",
        rating: 3.7,
        votes: 523,
        averageSalary: 145000,
        employmentRate: 85,
      },
      {
        collegeId: "20",
        collegeName: "Georgetown University",
        rating: 3.7,
        votes: 234,
        averageSalary: 144000,
        employmentRate: 81,
      },
      {
        collegeId: "19",
        collegeName: "Rice University",
        rating: 3.6,
        votes: 198,
        averageSalary: 142000,
        employmentRate: 80,
      },
      {
        collegeId: "5",
        collegeName: "Carnegie Mellon",
        rating: 3.5,
        votes: 176,
        averageSalary: 140000,
        employmentRate: 79,
      },
      { collegeId: "9", collegeName: "Caltech", rating: 3.4, votes: 154, averageSalary: 138000, employmentRate: 78 },
    ],
  },
  {
    profession: "Medicine",
    colleges: [
      {
        collegeId: "3",
        collegeName: "Harvard University",
        rating: 4.9,
        votes: 1234,
        averageSalary: 285000,
        employmentRate: 99,
      },
      {
        collegeId: "1",
        collegeName: "Stanford University",
        rating: 4.8,
        votes: 987,
        averageSalary: 278000,
        employmentRate: 98,
      },
      {
        collegeId: "13",
        collegeName: "Duke University",
        rating: 4.7,
        votes: 856,
        averageSalary: 275000,
        employmentRate: 97,
      },
      {
        collegeId: "14",
        collegeName: "University of Pennsylvania",
        rating: 4.6,
        votes: 743,
        averageSalary: 272000,
        employmentRate: 96,
      },
      {
        collegeId: "7",
        collegeName: "Yale University",
        rating: 4.6,
        votes: 689,
        averageSalary: 270000,
        employmentRate: 95,
      },
      {
        collegeId: "10",
        collegeName: "Columbia University",
        rating: 4.5,
        votes: 634,
        averageSalary: 268000,
        employmentRate: 94,
      },
      { collegeId: "2", collegeName: "MIT", rating: 4.4, votes: 234, averageSalary: 265000, employmentRate: 96 },
      {
        collegeId: "8",
        collegeName: "Princeton University",
        rating: 4.4,
        votes: 523,
        averageSalary: 263000,
        employmentRate: 93,
      },
      {
        collegeId: "11",
        collegeName: "University of Chicago",
        rating: 4.3,
        votes: 489,
        averageSalary: 260000,
        employmentRate: 92,
      },
      {
        collegeId: "12",
        collegeName: "Northwestern University",
        rating: 4.3,
        votes: 445,
        averageSalary: 258000,
        employmentRate: 91,
      },
      {
        collegeId: "4",
        collegeName: "UC Berkeley",
        rating: 4.2,
        votes: 567,
        averageSalary: 255000,
        employmentRate: 94,
      },
      {
        collegeId: "16",
        collegeName: "Brown University",
        rating: 4.2,
        votes: 378,
        averageSalary: 253000,
        employmentRate: 90,
      },
      {
        collegeId: "18",
        collegeName: "Vanderbilt University",
        rating: 4.1,
        votes: 334,
        averageSalary: 250000,
        employmentRate: 89,
      },
      {
        collegeId: "15",
        collegeName: "Cornell University",
        rating: 4.1,
        votes: 298,
        averageSalary: 248000,
        employmentRate: 88,
      },
      {
        collegeId: "17",
        collegeName: "Dartmouth College",
        rating: 4.0,
        votes: 267,
        averageSalary: 245000,
        employmentRate: 87,
      },
      {
        collegeId: "6",
        collegeName: "University of Texas at Austin",
        rating: 4.0,
        votes: 789,
        averageSalary: 245000,
        employmentRate: 93,
      },
      {
        collegeId: "19",
        collegeName: "Rice University",
        rating: 3.9,
        votes: 234,
        averageSalary: 242000,
        employmentRate: 86,
      },
      {
        collegeId: "20",
        collegeName: "Georgetown University",
        rating: 3.9,
        votes: 198,
        averageSalary: 240000,
        employmentRate: 85,
      },
      {
        collegeId: "5",
        collegeName: "Carnegie Mellon",
        rating: 3.8,
        votes: 176,
        averageSalary: 238000,
        employmentRate: 84,
      },
      { collegeId: "9", collegeName: "Caltech", rating: 3.7, votes: 154, averageSalary: 235000, employmentRate: 83 },
    ],
  },
]

export const mockUserRankings: UserRanking[] = [
  {
    userId: "user1",
    collegeId: "1",
    ratings: { academics: 5, campusLife: 4, careerServices: 5, facilities: 5, value: 3 },
    overall: 4.4,
    review: "Amazing academics and career opportunities, but very expensive.",
    profession: "Software Engineering",
  },
  {
    userId: "user2",
    collegeId: "2",
    ratings: { academics: 5, campusLife: 3, careerServices: 5, facilities: 4, value: 4 },
    overall: 4.2,
    review: "Incredible technical education, though campus life could be better.",
    profession: "Software Engineering",
  },
]
