/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Colleges {
  created_at: Generated<Timestamp | null>;
  discipline_id: Int8 | null;
  id: Generated<Int8>;
  logo: string | null;
  name: string;
  score: Int8 | null;
  type: string;
  updated_at: Generated<Timestamp | null>;
  votes: Generated<Int8 | null>;
}

export interface Comments {
  created_at: Generated<Timestamp | null>;
  id: Generated<Int8>;
  text: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Disciplines {
  created_at: Generated<Timestamp | null>;
  id: Generated<Int8>;
  name: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface DB {
  colleges: Colleges;
  comments: Comments;
  disciplines: Disciplines;
  users: Users;
}
